### ISSUE TITLE
Allow adding custom owner to query params

### ISSUE THREAD

**Issue by pablodoble** [pikselpalette/sequoia-js-client-sdk#84]
## Do you want to request a feature, ask a usage question, or report a bug?

Feature

### What is the current behavior?

At the moment, `resourceful_endpoint` adds the configured owner automatically to the query (`resourceful_endpoint:547`).

### What is the expected behavior?

It would be nice that this `owner` could be added in the query "on the fly" to make API calls for different owners without calling `setTenancy` each time.

**Comment by pablodoble** [comment]
I've got a solution for this almost ready... Would be happy to submit a PR.

**Comment by pablodoble** [comment]
Here's the PR: https://github.com/pikselpalette/sequoia-js-client-sdk/pull/85

**Comment by gerbilsinspace** [comment]
Merged
